name: QuantumROM Tools Sixteen.

on:
  workflow_dispatch:
    inputs:
      STOCK_DEVICE:
        description: "STOCK_DEVICE_MODEL or None"
        required: true
        default: "SM-G781B"
      USE_UI_8_TETHERING_APEX:
        description: "Set True if your kernel BPF version is 5.4 (lower than 5.10)."
        required: true
        default: "False"
      TARGET_DEVICE:
        description: "TARGET_DEVICE_MODEL."
        required: true
        default: "SM-S938B"
      TARGET_DEVICE_CSC:
        description: "TARGET_DEVICE_CSC."
        required: true
        default: "EUX"
      TARGET_DEVICE_IMEI:
        description: "TARGET_DEVICE_IMEI."
        required: true
        default: "354237928480904"
      OUTPUT_FILESYSTEM:
        description: "OUTPUT_FILESYSTEM. e.g erofs / ext4 / f2fs"
        required: true
        default: "erofs"
      COMPRESS_IMG_TO_XZ:
        description: "Compress IMG to XZ (True/False)"
        required: true
        default: "False"

jobs:
  build:
    name: Start QuantumROM Tools Sixteen.
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v4

      - name: Validate STOCK_DEVICE
        run: |
          STOCK_DEVICE="${{ github.event.inputs.STOCK_DEVICE }}"
          DEVICE_PATH="QuantumROM/Devices/$STOCK_DEVICE"
          if [ "$STOCK_DEVICE" != "None" ] && [ ! -d "$DEVICE_PATH" ]; then
            echo "❌ $STOCK_DEVICE is not supported with this tool."
            exit 1
          fi

      - name: Remove unnecessary files.
        uses: rokibhasansagar/slimhub_actions@v25.42.5

      - name: Install Dependencies.
        run: |
          sudo apt update
          sudo apt install -y p7zip-full lz4 liblz4-1 liblz4-dev libzstd1 libzstd-dev build-essential android-sdk-libsparse-utils f2fs-tools fuse2fs fuse e2fsprogs python3 python3-pip zipalign unzip openjdk-21-jdk jq perl xxd kmod erofs-utils linux-modules-extra-$(uname -r)
          sudo modprobe f2fs
          sudo pip3 install git+https://github.com/SN-Abdullah-Al-Noman/samloader.git --break-system-packages
          mkdir -p FW WORK OUT

      - name: Download firmware ▶️ ${{ github.event.inputs.TARGET_DEVICE }} - ${{ github.event.inputs.TARGET_DEVICE_CSC }}
        run: |
          source scripts/QuantumRom.sh
          DOWNLOAD_FIRMWARE "${{ github.event.inputs.TARGET_DEVICE }}" "${{ github.event.inputs.TARGET_DEVICE_CSC }}" "${{ github.event.inputs.TARGET_DEVICE_IMEI }}" "FW" "${{ github.event.inputs.TARGET_FW_VERSION }}"

      - name: Extract firmware
        run: |
          source scripts/QuantumRom.sh
          EXTRACT_FIRMWARE "FW/${{ github.event.inputs.TARGET_DEVICE }}"

      - name: Start Rom Build For ${{ github.event.inputs.STOCK_DEVICE }}
        run: |
          sudo bash sixteen.sh \
            "${{ github.event.inputs.STOCK_DEVICE }}" \
            "${{ github.event.inputs.USE_UI_8_TETHERING_APEX }}" \
            "${{ github.event.inputs.TARGET_DEVICE }}" \
            "${{ github.event.inputs.TARGET_DEVICE_CSC }}" \
            "${{ github.event.inputs.TARGET_DEVICE_IMEI }}" \
            "${{ github.event.inputs.OUTPUT_FILESYSTEM }}"

      - name: Compress all .img & make zip file before upload.
        run: |
          echo "BUILD_TIME=$(TZ='Asia/Dhaka' date '+%Y-%m-%d %I:%M:%S %p UTC+6')" >> $GITHUB_ENV
          OUT_DIR="$(pwd)/OUT"
          ZIP_NAME="${{ github.event.inputs.TARGET_DEVICE }}_Port_For_${{ github.event.inputs.STOCK_DEVICE }}.zip"
          ZIP_PATH="$OUT_DIR/$ZIP_NAME"

          if [ "${{ github.event.inputs.COMPRESS_IMG_TO_XZ }}" = "True" ]; then
            echo "Compressing all .img files to .xz (level 9)..."
            for img in "$OUT_DIR"/*.img; do
              [ -f "$img" ] || continue
              echo "Compressing $img"
              sudo xz -9 -T0 "$img"
            done
            sudo rm -f "$OUT_DIR"/*.img
          fi

          echo "Creating zip: $ZIP_NAME"
          7z a -tzip "$ZIP_PATH" "$OUT_DIR"/* -mx=5
          echo "ZIP_PATH=$ZIP_PATH" >> $GITHUB_ENV

      - name: Upload file in GoFile & Create Release.
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          STOCK_DEVICE: ${{ github.event.inputs.STOCK_DEVICE }}
          TARGET_DEVICE: ${{ github.event.inputs.TARGET_DEVICE }}
          OUTPUT_FILESYSTEM: ${{ github.event.inputs.OUTPUT_FILESYSTEM }}
          COMPRESS_IMG_TO_XZ: ${{ github.event.inputs.COMPRESS_IMG_TO_XZ }}
          USE_UI_8_TETHERING_APEX: ${{ github.event.inputs.USE_UI_8_TETHERING_APEX }}
        run: |
           bash release.sh
